### ISSUE TITLE
Add a individual chat

### ISSUE THREAD

**Issue by Astroxphiliauxx** [ossrndc/connectify#9]
Add a chat on home screen, by making changes in the home page.  Add a chat named - `Commit '24` and the subheading must be `Working on the first contribution`.

**Comment by somyapal111** [comment]
Assign me this issue

**Comment by somyapal111** [comment]
Assign me this issue

**Comment by prerna12s** [comment]
@p1r2i3n4c5e6 you can work on this issue now
